import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Navbar } from '../src/components/Navbar/Navbar'
import { Hero } from '../src/components/Hero/Hero'
import styles from '../styles/Home.module.css'
import { Welcome } from '../src/components/Welcome/Welcome'
import { Courses } from '../src/components/Course/Courses'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>AhmadouTech|Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class='dark'>
        <Navbar />
        <Hero />
        <Welcome />
        <Courses />
        
        <div className='relative bg-slate-100 dark:bg-slate-900 w-full h-60 ml-auto mr-auto  text-center'>
            <h1 className='rounded-lg shadow-2xl py-16 text-2xl text w-[80%]  text-[#2190ff] ml-auto mr-auto h-[80%]'>
               Sorry!!! For inconvienience As We Are Under Development Come Back Later SEE YU SOON
            </h1>
        </div>
      </main>
    </>
  )
}
