import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Navbar } from '../src/components/Navbar/Navbar'
import { Hero } from '../src/components/Hero/Hero'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>AhmadouTech|Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class='dark'>
        <Navbar />
        <Hero />
        <Hero />
        <Hero />
        <Hero />
        <Hero />
        <h1 className='text-color-black dark:text-white dark:bg-black text-center'>hello world</h1>
      </main>
    </>
  )
}
